import{a as i,S as m,i as p}from"./assets/vendor-7ecd423e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();i.defaults.headers.common["x-api-key"]="live_d6fCYBCjgVcrNcLCehO9h7vFE7XVmctgwsbaz8xbHaRGxDCAZX22e9BPeFKyzc7R";const h=()=>i.get("https://api.thecatapi.com/v1/breeds").then(o=>o.data),f=o=>i.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${o}`).then(t=>t.data),n=document.querySelector("#cat-breed-selector"),d=document.querySelector(".loader");document.addEventListener("DOMContentLoaded",()=>{h().then(o=>{const t=o.map(s=>({text:s.name,value:s.id}));new m({select:"#cat-breed-selector",data:[{text:"Select a cat breed",value:"",placeholder:!0},...t],placeholder:"Select a cat breed"}),l(),n.removeAttribute("hidden"),n.addEventListener("change",s=>g(s))}).catch(o=>{u(),console.log(o)})});const g=o=>{const t=o.target.value;t&&(console.log(t),n.setAttribute("disabled",""),d.removeAttribute("hidden"),f(t).then(s=>{const c=s[0],e=document.querySelector(".cat");e.innerHTML=`
          <div class="cat-img">
            <img src="${c.url}" alt="${c.id}" />
          </div>
          <div class="cat-info">
            <h2>${c.breeds[0].name}</h2>
            <p>${c.breeds[0].description}</p>
            <p><span class="temperament">Temprement: </span>${c.breeds[0].temperament}</p>
        </div>`,e.removeAttribute("hidden")}).catch(s=>{u(),console.log(s)}).finally(()=>{n.removeAttribute("disabled"),l()}))},l=()=>{d.style.display="none"};function u(){p.error({title:"Oops!",message:"Something went wrong. Please try reloading the page.",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
