import{a as d,S as u,i as m}from"./assets/vendor-7ecd423e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();d.defaults.headers.common["x-api-key"]="live_d6fCYBCjgVcrNcLCehO9h7vFE7XVmctgwsbaz8xbHaRGxDCAZX22e9BPeFKyzc7R";const p=()=>d.get("https://api.thecatapi.com/v1/breeds").then(o=>o.data),h=o=>d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${o}`).then(t=>t.data),c=document.querySelector("#cat-breed-selector"),a=document.querySelector("#loading");document.addEventListener("DOMContentLoaded",()=>{p().then(o=>{const t=o.map(s=>({text:s.name,value:s.id}));new u({select:"#cat-breed-selector",data:[{text:"Select a cat breed",value:"",placeholder:!0},...t],placeholder:"Select a cat breed"}),a.setAttribute("hidden",""),c.removeAttribute("hidden"),c.addEventListener("change",s=>f(s))}).catch(o=>{l(),console.log(o)})});const f=o=>{const t=o.target.value;t&&(console.log(t),c.setAttribute("disabled",""),a.removeAttribute("hidden"),h(t).then(s=>{const n=s[0],e=document.querySelector(".cat");e.innerHTML=`
          <div class="cat-img">
            <img src="${n.url}" alt="${n.id}" />
          </div>
          <div class="cat-info">
            <h2>${n.breeds[0].name}</h2>
            <p>${n.breeds[0].description}</p>
            <p><span class="temperament">Temprement: </span>${n.breeds[0].temperament}</p>
        </div>`,e.removeAttribute("hidden")}).catch(s=>{l(),console.log(s)}).finally(()=>{c.removeAttribute("disabled"),a.setAttribute("hidden","")}))};function l(){m.error({title:"Oops!",message:"Something went wrong. Please try reloading the page.",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
